-- CreateTable
CREATE TABLE "Member" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Round" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "course" TEXT NOT NULL,
    "note" TEXT
);

-- CreateTable
CREATE TABLE "Score" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "strokes" INTEGER NOT NULL,
    "h1" INTEGER NOT NULL,
    "h2" INTEGER NOT NULL,
    "h3" INTEGER NOT NULL,
    "h4" INTEGER NOT NULL,
    "h5" INTEGER NOT NULL,
    "h6" INTEGER NOT NULL,
    "h7" INTEGER NOT NULL,
    "h8" INTEGER NOT NULL,
    "h9" INTEGER NOT NULL,
    "h10" INTEGER NOT NULL,
    "h11" INTEGER NOT NULL,
    "h12" INTEGER NOT NULL,
    "h13" INTEGER NOT NULL,
    "h14" INTEGER NOT NULL,
    "h15" INTEGER NOT NULL,
    "h16" INTEGER NOT NULL,
    "h17" INTEGER NOT NULL,
    "h18" INTEGER NOT NULL,
    "memberId" INTEGER NOT NULL,
    "roundId" INTEGER NOT NULL,
    CONSTRAINT "Score_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Score_roundId_fkey" FOREIGN KEY ("roundId") REFERENCES "Round" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "GalleryItem" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "filePath" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateIndex
CREATE UNIQUE INDEX "Member_name_key" ON "Member"("name");
