-- CreateTable
CREATE TABLE `Member` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Member_name_key`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Course` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `par1` INTEGER NOT NULL DEFAULT 4,
    `par2` INTEGER NOT NULL DEFAULT 4,
    `par3` INTEGER NOT NULL DEFAULT 4,
    `par4` INTEGER NOT NULL DEFAULT 4,
    `par5` INTEGER NOT NULL DEFAULT 4,
    `par6` INTEGER NOT NULL DEFAULT 4,
    `par7` INTEGER NOT NULL DEFAULT 4,
    `par8` INTEGER NOT NULL DEFAULT 4,
    `par9` INTEGER NOT NULL DEFAULT 4,
    `par10` INTEGER NOT NULL DEFAULT 4,
    `par11` INTEGER NOT NULL DEFAULT 4,
    `par12` INTEGER NOT NULL DEFAULT 4,
    `par13` INTEGER NOT NULL DEFAULT 4,
    `par14` INTEGER NOT NULL DEFAULT 4,
    `par15` INTEGER NOT NULL DEFAULT 4,
    `par16` INTEGER NOT NULL DEFAULT 4,
    `par17` INTEGER NOT NULL DEFAULT 4,
    `par18` INTEGER NOT NULL DEFAULT 4,

    UNIQUE INDEX `Course_name_key`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Round` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `course` VARCHAR(191) NOT NULL,
    `note` VARCHAR(191) NULL,
    `scorecardImagePath` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Score` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `strokes` INTEGER NOT NULL,
    `h1` INTEGER NOT NULL,
    `h2` INTEGER NOT NULL,
    `h3` INTEGER NOT NULL,
    `h4` INTEGER NOT NULL,
    `h5` INTEGER NOT NULL,
    `h6` INTEGER NOT NULL,
    `h7` INTEGER NOT NULL,
    `h8` INTEGER NOT NULL,
    `h9` INTEGER NOT NULL,
    `h10` INTEGER NOT NULL,
    `h11` INTEGER NOT NULL,
    `h12` INTEGER NOT NULL,
    `h13` INTEGER NOT NULL,
    `h14` INTEGER NOT NULL,
    `h15` INTEGER NOT NULL,
    `h16` INTEGER NOT NULL,
    `h17` INTEGER NOT NULL,
    `h18` INTEGER NOT NULL,
    `memberId` INTEGER NOT NULL,
    `roundId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `GalleryItem` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NULL,
    `filePath` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Score` ADD CONSTRAINT `Score_memberId_fkey` FOREIGN KEY (`memberId`) REFERENCES `Member`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Score` ADD CONSTRAINT `Score_roundId_fkey` FOREIGN KEY (`roundId`) REFERENCES `Round`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
