-- CreateTable
CREATE TABLE "Course" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "par1" INTEGER NOT NULL DEFAULT 4,
    "par2" INTEGER NOT NULL DEFAULT 4,
    "par3" INTEGER NOT NULL DEFAULT 4,
    "par4" INTEGER NOT NULL DEFAULT 4,
    "par5" INTEGER NOT NULL DEFAULT 4,
    "par6" INTEGER NOT NULL DEFAULT 4,
    "par7" INTEGER NOT NULL DEFAULT 4,
    "par8" INTEGER NOT NULL DEFAULT 4,
    "par9" INTEGER NOT NULL DEFAULT 4,
    "par10" INTEGER NOT NULL DEFAULT 4,
    "par11" INTEGER NOT NULL DEFAULT 4,
    "par12" INTEGER NOT NULL DEFAULT 4,
    "par13" INTEGER NOT NULL DEFAULT 4,
    "par14" INTEGER NOT NULL DEFAULT 4,
    "par15" INTEGER NOT NULL DEFAULT 4,
    "par16" INTEGER NOT NULL DEFAULT 4,
    "par17" INTEGER NOT NULL DEFAULT 4,
    "par18" INTEGER NOT NULL DEFAULT 4
);

-- CreateIndex
CREATE UNIQUE INDEX "Course_name_key" ON "Course"("name");
